In [1]:
import numpy as np
import matplotlib.pyplot as plt
rng = np.random.RandomState(0)

**Question** Soit $\mathbf W$ une matrice de poids associée à un graphe non dirigé pondéré $G$ de $n$ noeuds et $\mathbf D$ sa matrice diagonale. Soit $\mathbf L = \mathbf D - \mathbf W$. Vérifier que $\mathbf L$ a un vecteur propre égal à $\mathbf 1_n$ (vecteur de $n$ valeurs égales à 1). Quelle est la valeur propre associée ? 

*Réponse* 

Pour la ligne $i$ on a $(\mathbf L\mathbf 1_n)_i = d_i-\sum_{j} \mathbf W_{ij}=0$. Donc $\mathbf L\mathbf 1_n$ est un vecteur de 0 et donc on a bien $\mathbf L\mathbf 1_n = 0*\mathbf 1_n$.

**Question** Charger le jeu de données breast cancer de sklearn. Construire une matrice de poids en utilisant un noyau Gaussien sur les attributs normalisés et vérifier cette propriété. 

In [2]:
from sklearn import datasets, preprocessing
X, y = datasets.load_breast_cancer(return_X_y=True)
scale = preprocessing.StandardScaler()
X = scale.fit_transform(X)

In [3]:
X.shape

(569, 30)

In [4]:
from sklearn.metrics.pairwise import pairwise_kernels
W1 = pairwise_kernels(X, metric="rbf")
W1 = W1 - np.eye(W1.shape[0])

In [5]:
L1 = np.diag(W1.sum(axis=1)) - W1

In [6]:
np.alltrue(np.isclose(L1@np.ones(L1.shape[0]), np.zeros(L1.shape[0])))

True

**Question** Avec les fonctions que vous avez créées lors du TP précédent, faire un graphe $G_2$ de 12 noeuds avec 3 composantes connexes : deux cercles, et un graphe complet. Afficher la matrice laplacienne et la décomposition spectrale. Quelle est la propriété de cette matrice laplacienne due au fait que le graphe a 3 composantes connexes ? Quelle est la multiplicité de la valeur propre 0 ?  Comparer les résultats avec la décomposition spectrale de la matrice laplacienne du cercle de taille 4.

In [7]:
def cercle(n):
    G = np.eye(n)
    G = np.vstack((G[-1],G[:-1]))
    G = G + G.T
    return G
def complet(n):
    return np.ones((n,n))-np.eye(n)

In [8]:
W2 = np.zeros((12,12))
W2[:4,:4] = cercle(4)
W2[4:8, 4:8] = complet(4)
W2[8:, 8:] = cercle(4)

In [9]:
L2 = np.diag(W2.sum(axis=1)) - W2
L2

array([[ 2., -1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  2., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  2., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0., -1.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  3., -1., -1., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  3., -1., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1., -1.,  3., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1., -1., -1.,  3.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2., -1.,  0., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  2., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  2., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0., -1.,  2.]])

In [10]:
def aff_dec_spec(L):
    E, V = np.linalg.eig(L)
    ind = np.argsort(np.abs(E))
    for i  in ind:
        print(E[i], V[:,i])

In [11]:
aff_dec_spec(L2)

-1.0616943338901568e-16 [ 0.   0.   0.   0.  -0.5 -0.5 -0.5 -0.5  0.   0.   0.   0. ]
-4.440892098500626e-16 [ 0.5  0.5  0.5  0.5 -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0. ]
-4.440892098500626e-16 [0.  0.  0.  0.  0.  0.  0.  0.  0.5 0.5 0.5 0.5]
2.0 [-3.33531670e-17 -7.07106781e-01  3.47371659e-16  7.07106781e-01
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
2.0 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -3.33531670e-17 -7.07106781e-01  3.47371659e-16  7.07106781e-01]
2.0000000000000004 [-7.07106781e-01  4.39271888e-16  7.07106781e-01  2.48474176e-16
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
2.0000000000000004 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000

In [12]:
aff_dec_spec(np.eye(4)*2 - cercle(4))


-4.440892098500626e-16 [0.5 0.5 0.5 0.5]
2.0 [-3.33531670e-17 -7.07106781e-01  3.47371659e-16  7.07106781e-01]
2.0000000000000004 [-7.07106781e-01  4.39271888e-16  7.07106781e-01  2.48474176e-16]
3.9999999999999982 [ 0.5 -0.5  0.5 -0.5]


**Question** Démontrez ce que vous avez observé.

*Réponse*


**Question** Observez quelle est la décomposition spectrale d'un graphe complet sur plusieurs exemples. 

In [13]:
aff_dec_spec(np.eye(10)*9 - complet(10))

-3.885780586188048e-16 [-0.31622777 -0.31622777 -0.31622777 -0.31622777 -0.31622777 -0.31622777
 -0.31622777 -0.31622777 -0.31622777 -0.31622777]
9.999999999999996 [ 0.0269557   0.25530447 -0.49149767  0.69226559 -0.32161695 -0.32161695
  0.04005145  0.04005145  0.04005145  0.04005145]
9.999999999999998 [-0.18296968 -0.6012231   0.77784776  0.00090643  0.00090643  0.00090643
  0.00090643  0.00090643  0.00090643  0.00090643]
9.999999999999998 [ 0.04073607  0.13656627 -0.17531919  0.17316734 -0.02783546 -0.00228681
 -0.36234825 -0.50727767  0.7277018  -0.00310412]
10.0 [ 0.9486833  -0.10540926 -0.10540926 -0.10540926 -0.10540926 -0.10540926
 -0.10540926 -0.10540926 -0.10540926 -0.10540926]
10.0 [ 0.2265915   0.89034436 -0.13961698 -0.13961698 -0.13961698 -0.13961698
 -0.13961698 -0.13961698 -0.13961698 -0.13961698]
10.0 [-0.16287042 -0.30122803  0.38153899 -0.06747121  0.51818438 -0.66489248
  0.0741847   0.0741847   0.0741847   0.0741847 ]
10.000000000000004 [ 0.01351121  0.01966407  0.

**Rappel** Si $\mathbf f$ est une fonction qui associe une valeur à chaque noeud, on rappelle que $\mathbf f^\top \mathbf L \mathbf f$ est la valeur de *smoothness* de $\mathbf f$, indiquant comment $\mathbf f$ est lisse sur le graphe. 



**Question** Quelles sont les fonctions qui sont les plus lisses possible sur un graphe. Vérifiez cela sur $G_1$, puis sur $G_2$. En quoi celles de $G_2$ sont différentes de celles de $G_1$ ?

*Réponse* 

- Fonctions constantes 
- Sur des graphes non connexes, constantes sur chaque composante connexe

**Question** Faire la version itérative sur un cercle de 10 noeuds. Les deux premiers noeuds sont étiquetés avec 1 et 0. Cette version itérative calcule la fonction harmonique en effectuant à chaque itération la moyenne des étiquettes des noeuds voisins (sauf pour les noeuds 0 et 1 qui restent fixés).

In [33]:
W = cercle(10)
f = np.zeros(10)
f[0] = 1
f[1] = 0

In [15]:
indices = set(range(10))
indices.remove(0)
indices.remove(1)
indices

{2, 3, 4, 5, 6, 7, 8, 9}

In [25]:
f_new = np.zeros(10)
f_cur = f.copy()
end_loop = False
while not end_loop:
    for i in indices:
        f_cur[i] = (f_new[(i+1)%10] + f_new[(i-1)%10]) / 2
    print(f_new)
    end_loop = np.alltrue(np.isclose(f_new, f_cur))
    f_new = f_cur
    f_cur = f_new.copy()    


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 1. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  -1.  -0.5  0.   0.   0.   0.   0.   0.   0.5]
[ 1.   -1.   -0.5  -0.25  0.    0.    0.    0.    0.25  0.5 ]
[ 1.    -1.    -0.625 -0.25  -0.125  0.     0.     0.125  0.25   0.625]
[ 1.     -1.     -0.625  -0.375  -0.125  -0.0625  0.0625  0.125   0.375
  0.625 ]
[ 1.      -1.      -0.6875  -0.375   -0.21875 -0.03125  0.03125  0.21875
  0.375    0.6875 ]
[ 1.       -1.       -0.6875   -0.453125 -0.203125 -0.09375   0.09375
  0.203125  0.453125  0.6875  ]
[ 1.        -1.        -0.7265625 -0.4453125 -0.2734375 -0.0546875
  0.0546875  0.2734375  0.4453125  0.7265625]
[ 1.         -1.         -0.72265625 -0.5        -0.25       -0.109375
  0.109375    0.25        0.5         0.72265625]
[ 1.         -1.         -0.75       -0.48632812 -0.3046875  -0.0703125
  0.0703125   0.3046875   0.48632812  0.75      ]
[ 1.         -1.         -0.74316406 -0.52734375 -0.27832031 -0.1171875
  0.1171875   0.27832031  0.5273437

**Question** Dans le cas général d'un graphe quelconque, de matrice de poids $\mathbf W$, pour un $i$ correspondant à un noeud non étiqueté, $f^{(t+1)}_i$ est la moyenne pondérée des valeurs $f^{(t)}_j$ pour tous les noeuds $j$ voisins de $i$.  

- Écrire la formule générale d'une itération de ce calcul, quel que soit le graphe. 


*Réponse*

 Soit pour un noeud $i$ non étiqueté

$$ f^{(t+1)}_i = \frac{1}{d_{i}}\sum_{j}^{n} \mathbf W_{ij} f^{(t)}_j$$


**Question** Reformuler cela mais avec la matrice stochastique $\mathbf P$ associée à $\mathbf W$

*Réponse* 

$$ f^{(t+1)}_i = \sum_{j}^{n} \mathbf P_{ij} f^{(t)}_j$$


**Question** Toujours sur ce cercle de 10 noeuds dont les deux premiers noeuds sont étiquetés avec 1 et 0, faire maintenant l'algorithme de Zhu et al 2003 en calculant la solution harmonique par la formule analytique donnée en cours.

In [26]:
Wul = W[2:, :2]
Wul

array([[0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.]])

In [27]:
Wuu = W[2:, 2:]
Wuu

array([[0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0.]])

In [28]:
fl = f[:2]
fl

array([ 1., -1.])

In [29]:
D = np.diag(W.sum(axis=1))

In [30]:
L = D - W
Luu = L[2:,2:]

In [31]:
fu = (np.linalg.inv(Luu))@Wul@fl

In [32]:
fu

array([-0.77777778, -0.55555556, -0.33333333, -0.11111111,  0.11111111,
        0.33333333,  0.55555556,  0.77777778])

**Question** Refaire la même chose mais en reprenant la matrice stochastique $\mathbf P$ associée à $\mathbf W$. Vérifiez que vous obtenez bien le même résultat.

In [37]:
P = W/W.sum(axis=1)
Pul = P[2:, :2]
Puu = P[2:, 2:]
PL = np.eye(10) - P
PLuu = PL[2:, 2:]
pfu = (np.linalg.inv(PLuu))@Pul@fl

In [38]:
pfu

array([-0.77777778, -0.55555556, -0.33333333, -0.11111111,  0.11111111,
        0.33333333,  0.55555556,  0.77777778])

**Question** Sur ce petit graphe, on applique maintenant la méthode de Zhou et al 2003. Construire la matrice $\mathbf S$

In [49]:
d = np.sum(W, axis=1)
D12 = np.diag(d**(-1/2))
S = D12@W@D12
S

array([[0. , 0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5],
       [0.5, 0. , 0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.5, 0. , 0.5, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.5, 0. , 0.5, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.5, 0. , 0.5, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.5, 0. , 0.5, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.5, 0. , 0.5, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.5, 0. , 0.5, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5, 0. , 0.5],
       [0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5, 0. ]])

**Question** Prendre une valeur de $\alpha=.99$. Faire la version itérative.

In [43]:
alpha = .99
f_cur = rng.random(10)
end_loop = False
while not end_loop:
    print(f_cur)
    f_new = alpha*S@f_cur + (1-alpha)*f
    end_loop = np.alltrue(np.allclose(f_new, f_cur))
    f_cur = f_new


[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]
[0.55382229 0.57003056 0.62373591 0.508077   0.58943476 0.4263148
 0.76114522 0.69361874 0.63123119 0.74867575]
[0.66275962 0.58289131 0.53366324 0.60051948 0.46252394 0.66853709
 0.5543671  0.68922632 0.71393577 0.58660147]
[0.58889893 0.59222932 0.58578834 0.49311265 0.628183   0.50336106
 0.67209289 0.62780992 0.63153476 0.68146422]
[0.6404783  0.5814702  0.53724427 0.60091582 0.49325449 0.64363657
 0.55992964 0.64529569 0.6480907  0.60411467]
[0.59686451 0.58297267 0.58528108 0.51009689 0.61605343 0.52132614
 0.63802147 0.59797007 0.61845813 0.63784165]
[0.61430309 0.58516207 0.54106943 0.59466058 0.5105544  0.62076707
 0.55405162 0.6219574  0.6117268  0.60158471]
[0.59743965 0.5719094  0.58401221 0.5205538  0.60163669 0.52697998
 0.61514861 0.57706032 0.60565334 0.6068848 ]
[0.59350313 0.58481867 0.54076928 0.58689621 0.51852922 0.60230872
 0.54649995 0.60429697 0.58605

 0.09344739 0.09620387 0.1009875  0.10770406]
[0.11662702 0.10774546 0.10093443 0.09624527 0.09339432 0.09251292
 0.09339432 0.09624527 0.10093443 0.10774546]
[0.116668   0.10769292 0.10097541 0.09619273 0.0934353  0.09246038
 0.0934353  0.09619273 0.10097541 0.10769292]
[0.11661599 0.10773349 0.10092339 0.0962333  0.09338329 0.09250095
 0.09338329 0.0962333  0.10092339 0.10773349]
[0.11665615 0.10768199 0.10096356 0.09618181 0.09342346 0.09244946
 0.09342346 0.09618181 0.10096356 0.10768199]
[0.11660517 0.10772176 0.10091258 0.09622157 0.09337248 0.09248922
 0.09337248 0.09622157 0.10091258 0.10772176]
[0.11664454 0.10767129 0.10095195 0.0961711  0.09341184 0.09243875
 0.09341184 0.0961711  0.10095195 0.10767129]
[0.11659458 0.10771026 0.10090198 0.09621008 0.09336188 0.09247773
 0.09336188 0.09621008 0.10090198 0.10771026]
[0.11663316 0.1076608  0.10094057 0.09616061 0.09340046 0.09242826
 0.09340046 0.09616061 0.10094057 0.1076608 ]
[0.11658419 0.107699   0.1008916  0.09619881 0.093

**Question** Calculer maintenant le résultat avec la formule analytique.

In [44]:
np.linalg.inv(np.eye(10)- alpha*S)@f

array([11.60726288, 10.71440694, 10.03800368,  9.56438837,  9.28399302,
        9.19115309,  9.28399302,  9.56438837, 10.03800368, 10.71440694])

**Question** Sur plusieurs jeux de données considérer une portion variable de données étiquetées et apprendre les étiquettes avec la méthode des fonctions harmoniques de Zhu et 2003,  et la méthode de Global-Local consistency de Zhou et al 2003. 

- Prendre les données de breast cancer 
- Prendre le problème des deux lunes, avec un noyau Gaussien, avec un knn graphe
- Prendre le jeu de données digits, avec noyau Gaussien, avec un knn graphe, considérer plusieurs problèmes binaires de votre choix à partir de ces données 
- Trouver un jeu de données public et essayer ces méthodes de classification

On prendra une règle de classification adaptée car les deux méthodes sont une relaxation réelle de ce problème discret. 

On fera une analyse en fonction de la taille des données étiquetées.